# Generated by Django 5.1.2 on 2024-11-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_whats_app', models.CharField(default='Somente números e sem espaço', max_length=11)),
                ('chave_api_whats_app', models.CharField(max_length=50)),
            ],
        ),
    ]
