# Generated by Django 5.1.2 on 2024-11-21 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_configwhatsapp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfigWhatsApp',
            new_name='Config_WhatsApp',
        ),
    ]
