# Generated by Django 5.1.2 on 2025-01-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_configwhatsapp_config_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='status_envelope',
            field=models.CharField(default='fa-envelope', max_length=18),
        ),
    ]
