name: Deploy

on:
  push:
    branches:
      - dev  # Branch que dispara o deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Check out code
        uses: actions/checkout@v3

      - name: 🔑 Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa  # Ajusta permissões
          ssh-keyscan -H "${{ secrets.HOST }}" >> ~/.ssh/known_hosts

      - name: 🚀 Deploy no Servidor
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER_NAME }}@${{ secrets.HOST }} << 'EOF'
            set -e  # Faz o script parar se algum comando falhar
            
            echo "📂 Acessando o diretório do projeto..."
            cd /srv/cotacaoplanounimed.com.br/www

            echo "🔄 Atualizando código do repositório..."
            git reset --hard  # Evita conflitos de merge
            git pull origin dev

            echo "📂 Entrando no projeto..."
            cd lpunimed2

            echo "🐍 Verificando ambiente virtual..."
            if [ ! -d "prod-venv" ]; then
                python3 -m venv prod-venv
            fi

            echo "🔄 Ativando ambiente virtual..."
            source prod-venv/bin/activate

            echo "📦 Instalando dependências..."
            pip install --upgrade pip
            pip install -r requirements.txt

            echo "📄 Aplicando migrações..."
            python manage.py makemigrations
            python manage.py migrate

            echo "🖼️ Coletando arquivos estáticos..."
            python manage.py collectstatic --noinput

            echo "🚀 Reiniciando serviços..."
            sudo systemctl restart uwsgi
            sudo systemctl restart nginx

            echo "✅ Deploy concluído com sucesso!"
          EOF
