name: Deploy

on:
  push:
    branches:
      - dev  # Substitua pela branch que deseja monitorar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa  # Corrige as permissões da chave privada
          ssh-keyscan -H "${{ secrets.HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy  
        run: |
          echo "${{ secrets.USER_NAME }}@${{ secrets.HOST }}"
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER_NAME }}@${{ secrets.HOST }} << 'EOF'
            # Caminho para o seu projeto no servidor
            cd /srv/cotacaoplanounimed.com.br/www
            # Baixar a versão mais recente do código
            git pull origin dev
            # Entrar no diretório do projeto
            cd lpunimed2
            # Verificar se o ambiente virtual já existe, senão criar
            if [ ! -d "prod-venv" ]; then
                python3 -m venv prod-venv
            fi
            # Ativar ambiente virtual
            source prod-venv/bin/activate
            # Instalar dependências
            pip install -r requirements.txt
            # Executar migrações (se for Django)
            python manage.py makemigrations
            python manage.py migrate
            # Coletar arquivos estáticos (se for Django)
            python manage.py collectstatic --noinput
            # Reiniciar uWSGI
            sudo systemctl restart uwsgi
            # Sair do diretório do projeto
            cd ..
            # Reiniciar Nginx
            sudo systemctl restart nginx
          EOF
